import type { Duration, Family, Season } from "./season.ts";

export type SlotKind =
  | "must"
  | "optional"
  | "calm"
  | "santa"
  | "santa-alt"
  | "transfer"
  | "flight"
  | "sauna";

export type CircuitDay = {
  n: number;
  night: string | null;
  transfer?: string;
  morning: string;
  afternoon: string;
  evening?: string;
  arrivalSensitive?: boolean;
  departureSensitive?: boolean;
  santaSlot?: "afternoon" | "morning";
  optionalSoutenu?: string;
};

export type Circuit = {
  id: string;
  title: string;
  tagline: string;
  duration: Duration;
  nights: number;
  families: Family[];
  seasons: Season[] | "all";
  winterOk: boolean;
  hub: "HEL" | "RVN";
  transport: string;
  nightsSummary: string;
  firstCity: string;
  cities: string[];
  days: CircuitDay[];
  notes: string[];
  /** 15 j = assemblage d’ossatures existantes, pas un noyau 10 j. */
  composition?: { scheme: string; parts: string[] };
};

export const CIRCUITS: Circuit[] = [
  {
    id: "we-helsinki",
    title: "Long week-end à Helsinki",
    tagline: "La capitale, Suomenlinna, un vrai sauna. On ne pretend pas voir la Finlande.",
    duration: 3,
    nights: 2,
    families: ["indispensables", "unesco-bois", "cote-archipel"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Transports urbains, pas de voiture",
    nightsSummary: "Helsinki ×2",
    firstCity: "Helsinki",
    cities: ["Helsinki"],
    notes: ["Porvoo en aller-retour seulement si le vol retour est après 16 h."],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport → centre ~30 min",
        morning: "Senaatintori, Tuomiokirkko, Uspenski",
        afternoon: "Promenade centre, Kauppatori / halle",
        evening: "Allas ou Löyly, ou shopping Stockmann",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry Suomenlinna ~20 min",
        morning: "Suomenlinna UNESCO (3 h)",
        afternoon: "Temppeliaukio, Oodi, Design District",
        evening: "Sauna si pas fait J1",
      },
      {
        n: 3,
        night: null,
        transfer: "Train aéroport ~30 min",
        morning: "Porvoo A/R ou Amos Rex / Kiasma",
        afternoon: "Aéroport",
        departureSensitive: true,
        optionalSoutenu: "Porvoo en aller-retour (~1 h)",
      },
    ],
  },
  {
    id: "unesco-bois",
    title: "UNESCO et villes de bois",
    tagline: "Helsinki, Porvoo, Turku, Rauma. L’arrivée à l’aéroport est dans le circuit.",
    duration: 7,
    nights: 6,
    families: ["unesco-bois"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Voiture J3 → J7 (ou bus, sans Sammallahdenmäki)",
    nightsSummary: "Helsinki ×2 · Porvoo ×1 · Turku ×1 · Rauma ×2",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Porvoo", "Turku", "Rauma"],
    notes: [
      "On reste à Helsinki J1 — pas de saut vers Turku.",
      "Petäjävesi n’est pas sur cette route.",
    ],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport → centre",
        morning: "Centre historique",
        afternoon: "Calme centre / shopping",
        evening: "Sauna doux (Allas)",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna UNESCO",
        afternoon: "Temppeliaukio, Oodi, Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Porvoo",
        transfer: "Helsinki → Porvoo ~50 min",
        morning: "Vieille ville bois, cathédrale",
        afternoon: "Entrepôts rouges, colline",
        evening: "Dîner local",
      },
      {
        n: 4,
        night: "Turku",
        transfer: "Porvoo → Turku ~2 h 15",
        morning: "Route. Pause Fiskars si rythme soutenu",
        afternoon: "Château, cathédrale, Aura",
        evening: "Centre Turku",
        optionalSoutenu: "Pause Fiskars (+45 min)",
      },
      {
        n: 5,
        night: "Rauma",
        transfer: "Turku → Rauma ~1 h 30",
        morning: "Naantali vieille ville en chemin",
        afternoon: "Old Rauma UNESCO, café Kontion",
        evening: "Bois le soir",
      },
      {
        n: 6,
        night: "Rauma",
        morning: "Sammallahdenmäki UNESCO (~20 min)",
        afternoon: "Rauma libre / musée maritime",
        evening: "Calme",
      },
      {
        n: 7,
        night: null,
        transfer: "Rauma → HEL ~3 h",
        morning: "Route. Pause Tampere si vol du soir",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "triangle",
    title: "Triangle d’or",
    tagline: "Helsinki, Tampere, Turku — le premier séjour le plus sûr, toute saison, en train.",
    duration: 7,
    nights: 6,
    families: ["indispensables", "cote-archipel"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Trains. Pas de voiture.",
    nightsSummary: "Helsinki ×2 · Tampere ×2 · Turku ×2",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Tampere", "Turku"],
    notes: ["Rauma = option J6 si rythme soutenu, pas une nuit."],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport → centre",
        morning: "Senaatintori, marché",
        afternoon: "Calme si vol tard",
        evening: "Allas / Löyly",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna",
        afternoon: "Temppeliaukio, Oodi, Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Tampere",
        transfer: "Train HEL–TRE ~1 h 40",
        morning: "Arrivée, Pyynikki + donuts",
        afternoon: "Finlayson, Tammerkoski",
        evening: "Sauna Rajaportti ou Kuuma",
      },
      {
        n: 4,
        night: "Tampere",
        morning: "Vapriikki ou Moominmuseum / Näsinneula",
        afternoon: "Deuxième sauna ou Pispala",
        evening: "Calme",
      },
      {
        n: 5,
        night: "Turku",
        transfer: "Train TRE–TKU ~1 h 50",
        morning: "Château de Turku",
        afternoon: "Cathédrale, Aura, halle",
        evening: "Centre",
      },
      {
        n: 6,
        night: "Turku",
        morning: "Naantali vieille ville",
        afternoon: "Turku libre / Kakola",
        evening: "Dîner Aura",
        optionalSoutenu: "Rauma A/R ~1 h 30",
      },
      {
        n: 7,
        night: null,
        transfer: "Train Turku → HEL aéroport ~2 h 30",
        morning: "Matin Turku si vol après 17 h",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "laponie-express",
    title: "Laponie express",
    tagline: "Helsinki tampon, Rovaniemi, retour Helsinki. Pas d’open-jaw.",
    duration: 7,
    nights: 6,
    families: ["aurores-laponie"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Vol intérieur HEL–RVN–HEL (train de nuit = variante éco)",
    nightsSummary: "Helsinki ×2 · Rovaniemi ×4",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Rovaniemi"],
    notes: [
      "Dernière nuit à Helsinki.",
      "Village du Père Noël = créneau remplaçable.",
      "Pas d’Inari, Levi, Cap Nord.",
    ],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport → centre",
        morning: "Centre Helsinki",
        afternoon: "Calme si vol tard",
        evening: "Dîner Helsinki. Pas de vol RVN ce soir",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Rovaniemi",
        transfer: "Vol HEL → RVN ~1 h 15",
        morning: "Vol, installation",
        afternoon: "Village du Père Noël (½ j) ou remplaçant",
        evening: "Première chasse aurores si saison sombre",
        santaSlot: "afternoon",
      },
      {
        n: 3,
        night: "Rovaniemi",
        morning: "Husky (hiver) / chenil + balade",
        afternoon: "Ferme de rennes",
        evening: "Aurores guidées",
      },
      {
        n: 4,
        night: "Rovaniemi",
        morning: "Arktikum",
        afternoon: "Ounasvaara / ville",
        evening: "Aurores ou sauna",
      },
      {
        n: 5,
        night: "Rovaniemi",
        morning: "Libre / raquettes / Ranua",
        afternoon: "Calme nord",
        evening: "Dernière nuit Laponie",
      },
      {
        n: 6,
        night: "Helsinki",
        transfer: "Vol RVN → HEL après-midi",
        morning: "Matin calme Rovaniemi",
        afternoon: "Vol, arrivée Helsinki tampon",
        evening: "Calme Helsinki",
      },
      {
        n: 7,
        night: null,
        transfer: "Train aéroport ~30 min",
        morning: "Selon vol international",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "cote-sud",
    title: "Road trip côte et sud",
    tagline: "Les meilleurs lieux du sud. Voiture. Archipel 1 nuit, pas un trail vélo.",
    duration: 10,
    nights: 9,
    families: ["cote-archipel", "unesco-bois", "indispensables"],
    seasons: ["printemps", "ete", "automne"],
    winterOk: false,
    hub: "HEL",
    transport: "Voiture J3 → J10",
    nightsSummary: "Helsinki ×2 · Turku ×2 · archipel ×1 · Rauma ×2 · Tampere ×2",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Porvoo", "Turku", "Naantali", "Rauma", "Tampere"],
    notes: ["En hiver cette ossature est fermée — on bascule vers le mix Helsinki + Laponie."],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport",
        morning: "Centre selon vol",
        afternoon: "Calme si tard",
        evening: "Sauna",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna",
        afternoon: "Ville / Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Turku",
        transfer: "Voiture HEL → Porvoo → Turku",
        morning: "Porvoo (stop, pas une nuit)",
        afternoon: "Route ouest, arrivée Turku",
        evening: "Aura",
      },
      {
        n: 4,
        night: "Turku",
        morning: "Château + cathédrale",
        afternoon: "Naantali vieille ville",
        evening: "Turku",
      },
      {
        n: 5,
        night: "Nauvo ou Naantali",
        transfer: "Ferry archipel (été) / route courte (épaule)",
        morning: "Archipel : Nauvo l’été, Naantali l’épaule",
        afternoon: "Village, mer, sauna chalet",
        evening: "Archipel",
      },
      {
        n: 6,
        night: "Rauma",
        transfer: "~1 h 30–2 h",
        morning: "Route côtière",
        afternoon: "Old Rauma UNESCO",
        evening: "Bois",
      },
      {
        n: 7,
        night: "Rauma",
        morning: "Sammallahdenmäki UNESCO",
        afternoon: "Rauma libre",
        evening: "Calme",
      },
      {
        n: 8,
        night: "Tampere",
        transfer: "~1 h 45",
        morning: "Route intérieure",
        afternoon: "Pyynikki, Finlayson",
        evening: "Sauna Tampere",
      },
      {
        n: 9,
        night: "Tampere",
        morning: "Sauna / musée",
        afternoon: "Libre",
        evening: "Dernière nuit sud",
        optionalSoutenu: "Détour Petäjävesi si ouvert",
      },
      {
        n: 10,
        night: null,
        transfer: "Tampere → HEL aéroport ~1 h 40",
        morning: "Selon vol",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "mix-hel-lap",
    title: "Helsinki + Laponie",
    tagline: "Trois vrais jours au sud, cinq nuits au nord, nuit tampon à Helsinki. Pas d’open-jaw.",
    duration: 10,
    nights: 9,
    families: ["indispensables", "aurores-laponie"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Vols intérieurs HEL–RVN–HEL",
    nightsSummary: "Helsinki ×4 · Rovaniemi ×5",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Rovaniemi"],
    notes: [
      "Turku + Rauma + Laponie en 10 j = trop de bitume.",
      "Santa = créneau remplaçable.",
    ],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport",
        morning: "Centre selon vol",
        afternoon: "Calme si tard",
        evening: "Sauna doux",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna UNESCO",
        afternoon: "Temppeliaukio, Oodi, Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Helsinki",
        morning: "Porvoo ou Nuuksio (½–1 j)",
        afternoon: "Retour Helsinki",
        evening: "Libre",
      },
      {
        n: 4,
        night: "Rovaniemi",
        transfer: "Vol HEL → RVN matin",
        morning: "Vol + installation",
        afternoon: "Village du Père Noël (½ j) ou remplaçant",
        evening: "Aurores si saison",
        santaSlot: "afternoon",
      },
      {
        n: 5,
        night: "Rovaniemi",
        morning: "Husky / chenil",
        afternoon: "Rennes",
        evening: "Aurores",
      },
      {
        n: 6,
        night: "Rovaniemi",
        morning: "Arktikum",
        afternoon: "Ville / Ounasvaara",
        evening: "Aurores",
      },
      {
        n: 7,
        night: "Rovaniemi",
        morning: "Nature / Ranua",
        afternoon: "Libre",
        evening: "Igloo option budget plus",
      },
      {
        n: 8,
        night: "Rovaniemi",
        morning: "Journée nature",
        afternoon: "Sauna",
        evening: "Dernière chasse",
      },
      {
        n: 9,
        night: "Helsinki",
        transfer: "Vol RVN → HEL après-midi",
        morning: "Matin calme Rovaniemi",
        afternoon: "Arrivée Helsinki, tampon",
        evening: "Calme / shopping",
      },
      {
        n: 10,
        night: null,
        transfer: "Train aéroport",
        morning: "Selon vol international",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "triangle-laponie",
    title: "Triangle + Laponie",
    tagline: "Une semaine au sud en train, une semaine au nord. A/R Helsinki, pas d’open-jaw.",
    duration: 15,
    nights: 14,
    families: ["indispensables", "aurores-laponie"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Trains sud, puis vols HEL–RVN–HEL",
    nightsSummary: "Helsinki ×4 · Tampere ×2 · Turku ×2 · Rovaniemi ×6",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Tampere", "Turku", "Rovaniemi"],
    composition: { scheme: "7 j + 8 j", parts: ["Triangle d’or", "Laponie express"] },
    notes: [
      "J7 est le pont : Turku → vol RVN. Pas deux arrivées.",
      "Dernière nuit à Helsinki.",
      "Santa = créneau remplaçable.",
    ],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport → centre",
        morning: "Senaatintori, marché",
        afternoon: "Calme si vol tard",
        evening: "Allas / Löyly",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna",
        afternoon: "Temppeliaukio, Oodi, Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Tampere",
        transfer: "Train HEL–TRE ~1 h 40",
        morning: "Arrivée, Pyynikki + donuts",
        afternoon: "Finlayson, Tammerkoski",
        evening: "Sauna Rajaportti ou Kuuma",
      },
      {
        n: 4,
        night: "Tampere",
        morning: "Vapriikki ou Moominmuseum / Näsinneula",
        afternoon: "Deuxième sauna ou Pispala",
        evening: "Calme",
      },
      {
        n: 5,
        night: "Turku",
        transfer: "Train TRE–TKU ~1 h 50",
        morning: "Château de Turku",
        afternoon: "Cathédrale, Aura, halle",
        evening: "Centre",
      },
      {
        n: 6,
        night: "Turku",
        morning: "Naantali vieille ville",
        afternoon: "Turku libre / Kakola",
        evening: "Dîner Aura",
        optionalSoutenu: "Rauma A/R ~1 h 30",
      },
      {
        n: 7,
        night: "Rovaniemi",
        transfer: "Train Turku → HEL, vol HEL → RVN",
        morning: "Départ Turku, transit Helsinki",
        afternoon: "Vol, installation Rovaniemi",
        evening: "Première chasse aurores si saison sombre",
      },
      {
        n: 8,
        night: "Rovaniemi",
        morning: "Cercle polaire",
        afternoon: "Village du Père Noël (½ j) ou remplaçant",
        evening: "Aurores",
        santaSlot: "afternoon",
      },
      {
        n: 9,
        night: "Rovaniemi",
        morning: "Husky (hiver) / chenil + balade",
        afternoon: "Ferme de rennes",
        evening: "Aurores guidées",
      },
      {
        n: 10,
        night: "Rovaniemi",
        morning: "Arktikum",
        afternoon: "Ounasvaara / ville",
        evening: "Aurores ou sauna",
      },
      {
        n: 11,
        night: "Rovaniemi",
        morning: "Libre / raquettes / Ranua",
        afternoon: "Calme nord",
        evening: "Aurores",
      },
      {
        n: 12,
        night: "Rovaniemi",
        morning: "Nature, pas Inari ni Levi",
        afternoon: "Sauna",
        evening: "Dernière nuit Laponie",
      },
      {
        n: 13,
        night: "Helsinki",
        transfer: "Vol RVN → HEL après-midi",
        morning: "Matin calme Rovaniemi",
        afternoon: "Vol, tampon Helsinki",
        evening: "Calme Helsinki",
      },
      {
        n: 14,
        night: "Helsinki",
        morning: "Shopping, musée, île si météo",
        afternoon: "Sauna ou Design District",
        evening: "Dernière soirée",
      },
      {
        n: 15,
        night: null,
        transfer: "Train aéroport ~30 min",
        morning: "Selon vol international",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "cote-plus",
    title: "Côte 10 j + 5 j sud",
    tagline: "Le road trip côte, plus Porvoo, un vrai archipel, et un tampon Helsinki. Pas de Laponie.",
    duration: 15,
    nights: 14,
    families: ["cote-archipel", "unesco-bois", "indispensables"],
    seasons: ["printemps", "ete", "automne"],
    winterOk: false,
    hub: "HEL",
    transport: "Voiture J4 → J13",
    nightsSummary: "Helsinki ×5 · Porvoo ×1 · Turku ×2 · archipel ×2 · Rauma ×2 · Tampere ×2",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Porvoo", "Turku", "Naantali", "Rauma", "Tampere"],
    composition: { scheme: "10 j + 5 j", parts: ["Road trip côte et sud", "Helsinki / Porvoo / archipel"] },
    notes: ["Fermé en hiver — on bascule vers Triangle + Laponie."],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport",
        morning: "Centre selon vol",
        afternoon: "Calme si tard",
        evening: "Sauna",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna",
        afternoon: "Ville / Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Helsinki",
        morning: "Nuuksio ou musées",
        afternoon: "Oodi, halle, île",
        evening: "Libre",
      },
      {
        n: 4,
        night: "Porvoo",
        transfer: "Helsinki → Porvoo ~50 min",
        morning: "Vieille ville bois",
        afternoon: "Entrepôts, colline",
        evening: "Nuit Porvoo",
      },
      {
        n: 5,
        night: "Turku",
        transfer: "Porvoo → Turku ~2 h 15",
        morning: "Route. Fiskars si rythme soutenu",
        afternoon: "Arrivée Turku, Aura",
        evening: "Centre",
        optionalSoutenu: "Pause Fiskars",
      },
      {
        n: 6,
        night: "Turku",
        morning: "Château + cathédrale",
        afternoon: "Naantali vieille ville",
        evening: "Turku",
      },
      {
        n: 7,
        night: "Nauvo ou Naantali",
        transfer: "Ferry archipel (été) / route courte (épaule)",
        morning: "Archipel : Nauvo l’été, Naantali l’épaule",
        afternoon: "Village, mer, sauna chalet",
        evening: "Archipel",
      },
      {
        n: 8,
        night: "Nauvo ou Naantali",
        morning: "Deuxième jour mer, pas un trail",
        afternoon: "Île voisine ou farniente",
        evening: "Archipel",
      },
      {
        n: 9,
        night: "Rauma",
        transfer: "~1 h 30–2 h",
        morning: "Route côtière",
        afternoon: "Old Rauma UNESCO",
        evening: "Bois",
      },
      {
        n: 10,
        night: "Rauma",
        morning: "Sammallahdenmäki UNESCO",
        afternoon: "Rauma libre",
        evening: "Calme",
      },
      {
        n: 11,
        night: "Tampere",
        transfer: "~1 h 45",
        morning: "Route intérieure",
        afternoon: "Pyynikki, Finlayson",
        evening: "Sauna Tampere",
      },
      {
        n: 12,
        night: "Tampere",
        morning: "Sauna / musée",
        afternoon: "Libre",
        evening: "Dernière nuit intérieure",
        optionalSoutenu: "Détour Petäjävesi si ouvert",
      },
      {
        n: 13,
        night: "Helsinki",
        transfer: "Tampere → Helsinki ~1 h 40",
        morning: "Route ou train",
        afternoon: "Tampon Helsinki",
        evening: "Ville",
      },
      {
        n: 14,
        night: "Helsinki",
        morning: "Libre, shopping, île",
        afternoon: "Sauna",
        evening: "Dernière soirée",
      },
      {
        n: 15,
        night: null,
        transfer: "Train aéroport",
        morning: "Selon vol international",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
  {
    id: "mix-plus",
    title: "Helsinki + Laponie longue",
    tagline: "Le mix 10 j, plus 5 nuits au nord. Moins de villes du sud, plus d’aurores.",
    duration: 15,
    nights: 14,
    families: ["indispensables", "aurores-laponie"],
    seasons: "all",
    winterOk: true,
    hub: "HEL",
    transport: "Vols intérieurs HEL–RVN–HEL",
    nightsSummary: "Helsinki ×6 · Rovaniemi ×8",
    firstCity: "Helsinki",
    cities: ["Helsinki", "Rovaniemi"],
    composition: { scheme: "10 j + 5 j", parts: ["Helsinki + Laponie", "5 nuits nord en plus"] },
    notes: [
      "Pas Tampere ni Turku : le 5 j en plus va au nord, pas à un deuxième road trip.",
      "Santa = créneau remplaçable.",
    ],
    days: [
      {
        n: 1,
        night: "Helsinki",
        transfer: "Aéroport",
        morning: "Centre selon vol",
        afternoon: "Calme si tard",
        evening: "Sauna doux",
        arrivalSensitive: true,
      },
      {
        n: 2,
        night: "Helsinki",
        transfer: "Ferry",
        morning: "Suomenlinna UNESCO",
        afternoon: "Temppeliaukio, Oodi, Design",
        evening: "Libre",
      },
      {
        n: 3,
        night: "Helsinki",
        morning: "Porvoo ou Nuuksio (½–1 j)",
        afternoon: "Retour Helsinki",
        evening: "Libre",
      },
      {
        n: 4,
        night: "Rovaniemi",
        transfer: "Vol HEL → RVN matin",
        morning: "Vol + installation",
        afternoon: "Village du Père Noël (½ j) ou remplaçant",
        evening: "Aurores si saison",
        santaSlot: "afternoon",
      },
      {
        n: 5,
        night: "Rovaniemi",
        morning: "Husky / chenil",
        afternoon: "Rennes",
        evening: "Aurores",
      },
      {
        n: 6,
        night: "Rovaniemi",
        morning: "Arktikum",
        afternoon: "Ville / Ounasvaara",
        evening: "Aurores",
      },
      {
        n: 7,
        night: "Rovaniemi",
        morning: "Nature / Ranua",
        afternoon: "Libre",
        evening: "Igloo option budget plus",
      },
      {
        n: 8,
        night: "Rovaniemi",
        morning: "Raquettes ou deuxième nature",
        afternoon: "Calme",
        evening: "Aurores",
      },
      {
        n: 9,
        night: "Rovaniemi",
        morning: "Journée libre nord",
        afternoon: "Sauna",
        evening: "Aurores",
      },
      {
        n: 10,
        night: "Rovaniemi",
        morning: "Pas Inari, pas Levi",
        afternoon: "Village ou forêt",
        evening: "Aurores",
      },
      {
        n: 11,
        night: "Rovaniemi",
        morning: "Dernière activité nord",
        afternoon: "Souple",
        evening: "Dernière chasse",
      },
      {
        n: 12,
        night: "Helsinki",
        transfer: "Vol RVN → HEL après-midi",
        morning: "Matin calme Rovaniemi",
        afternoon: "Arrivée Helsinki, tampon",
        evening: "Calme / shopping",
      },
      {
        n: 13,
        night: "Helsinki",
        morning: "Île, musée, café",
        afternoon: "Libre",
        evening: "Ville",
      },
      {
        n: 14,
        night: "Helsinki",
        morning: "Dernier sauna ou shopping",
        afternoon: "Souple",
        evening: "Dernière soirée",
      },
      {
        n: 15,
        night: null,
        transfer: "Train aéroport",
        morning: "Selon vol international",
        afternoon: "Aéroport",
        departureSensitive: true,
      },
    ],
  },
];

export function circuitById(id: string): Circuit | undefined {
  return CIRCUITS.find((c) => c.id === id);
}
